/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASIGNACION = 6;
  /** RegularExpression Id. */
  int MAS = 7;
  /** RegularExpression Id. */
  int MENOS = 8;
  /** RegularExpression Id. */
  int MULTIPLICAR = 9;
  /** RegularExpression Id. */
  int DIVIDIR = 10;
  /** RegularExpression Id. */
  int INCR = 11;
  /** RegularExpression Id. */
  int DECR = 12;
  /** RegularExpression Id. */
  int MODULO = 13;
  /** RegularExpression Id. */
  int SUMAIGUAL = 14;
  /** RegularExpression Id. */
  int RESTAIGUAL = 15;
  /** RegularExpression Id. */
  int MULTIGUAL = 16;
  /** RegularExpression Id. */
  int DIVIDIRIGUAL = 17;
  /** RegularExpression Id. */
  int MODULOIGUAL = 18;
  /** RegularExpression Id. */
  int MAIN = 19;
  /** RegularExpression Id. */
  int WRITE = 20;
  /** RegularExpression Id. */
  int READ = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int BREAK = 24;
  /** RegularExpression Id. */
  int FOR = 25;
  /** RegularExpression Id. */
  int WHILE = 26;
  /** RegularExpression Id. */
  int PARI = 27;
  /** RegularExpression Id. */
  int PARD = 28;
  /** RegularExpression Id. */
  int LLAVEI = 29;
  /** RegularExpression Id. */
  int LLAVED = 30;
  /** RegularExpression Id. */
  int DELIMITER = 31;
  /** RegularExpression Id. */
  int COMA = 32;
  /** RegularExpression Id. */
  int COMILLA = 33;
  /** RegularExpression Id. */
  int COMENTARIO = 34;
  /** RegularExpression Id. */
  int IGUALDAD = 35;
  /** RegularExpression Id. */
  int MAYOR = 36;
  /** RegularExpression Id. */
  int MAYORI = 37;
  /** RegularExpression Id. */
  int MENOR = 38;
  /** RegularExpression Id. */
  int MENORI = 39;
  /** RegularExpression Id. */
  int DIFERENCIA = 40;
  /** RegularExpression Id. */
  int NEGACION = 41;
  /** RegularExpression Id. */
  int AND = 42;
  /** RegularExpression Id. */
  int OR = 43;
  /** RegularExpression Id. */
  int TRUE = 44;
  /** RegularExpression Id. */
  int FALSE = 45;
  /** RegularExpression Id. */
  int NULL = 46;
  /** RegularExpression Id. */
  int INT = 47;
  /** RegularExpression Id. */
  int FLOAT = 48;
  /** RegularExpression Id. */
  int STRING = 49;
  /** RegularExpression Id. */
  int BOOL = 50;
  /** RegularExpression Id. */
  int CARACTER = 51;
  /** RegularExpression Id. */
  int NUMERO = 52;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 53;
  /** RegularExpression Id. */
  int DECIMAL = 54;
  /** RegularExpression Id. */
  int CADENA = 55;
  /** RegularExpression Id. */
  int CHAR = 56;
  /** RegularExpression Id. */
  int ERRORES = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"++\"",
    "\"--\"",
    "\"%\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"principal\"",
    "\"imprimir\"",
    "\"leer\"",
    "\"cuando\"",
    "\"sino\"",
    "\"romper\"",
    "\"ciclo_for\"",
    "\"ciclo_mientras\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"\\\"\"",
    "\"#\"",
    "\"==\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"!=\"",
    "\"!\"",
    "\"&&\"",
    "\"||\"",
    "\"verdadero\"",
    "\"falso\"",
    "\"nulo\"",
    "\"entero\"",
    "\"flotante\"",
    "\"cadena\"",
    "\"bool\"",
    "\"caracter\"",
    "<NUMERO>",
    "<IDENTIFICADOR>",
    "<DECIMAL>",
    "<CADENA>",
    "<CHAR>",
    "<ERRORES>",
  };

}
